spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/Chendapeng1019/Spring-Cloud-Qianfeng.git
          search-paths: spring-cloud-config
          username: 714491235@qq.com
          password: 15079011662Cdp

server:
  port: 8888

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/